spring:
  data:
    mongodb:
      username: ${MONGO_USERNAME:adnan}
      password: ${MONGO_PASSWORD:adnan}
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27018}
      database: ${MONGO_DATABASE:customer}
      authentication-database: ${MONGO_AUTH_DB:admin}

server:
  port: 8090
