spring:
  data:
    mongodb:
      username: ${MONGO_USERNAME:adnan}
      password: ${MONGO_PASSWORD:adnan}
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27018}
      database: ${MONGO_DATABASE:customer}
      authentication-database: ${MONGO_AUTH_DB:admin}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      group-id: ${CONSUMER_GROUP:orderGroup}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.invilen.notification.dto.OrderConfirmation
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:adnan}
    password: ${MAIL_PASSWORD:adnan}
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040
